User.delete_all
Playlist.delete_all


user1 = User.create(name: "Jason")
user2 = User.create(name: "David")

december2019 = Playlist.create(name: "December 2019", user_id: user1.id)
january2020 = Playlist.create(name: "January 2020", user_id: user1.id)
february2020 = Playlist.create(name: "February 2020", user_id: user2.id)


song1 = Song.create(name: "youmakemefloetic", artist: "cay caleb", genre: "R&B", platform: "SoundCloud")
song2 = Song.create(name: "Back To The Future", artist: "Magic Flowers", genre: "Hip-hop", platform: "SoundCloud")
song3 = Song.create(name: "controlla (camoufly's take)", artist: "camoufly", genre: "Hip-hop", platform: "SoundCloud")
song4 = Song.create(name: "Wabi Sabi Edit", artist: "Pryces Trash Can", genre: "Soul", platform: "SoundCloud")
song5 = Song.create(name: "Meditate", artist: "EarthGang", genre: "Rap", platform: "SoundCloud")
song6 = Song.create(name: "Sofasound x Foolie $ufin' - X", artist: "Sofasound", genre: "Pop", platform: "SoundCloud")
song7 = Song.create(name: "N O N S T O P (Ticklish Reboot)", artist: "TICKLISH", genre: "Pop", platform: "SoundCloud")
song8 = Song.create(name: "Risk feat. Bas", artist: "FKJ", genre: "Soul", platform: "Spotify")
song9 = Song.create(name: "Love", artist: "DON MAYOR", genre: "Soul", platform: "SoundCloud")
song10 = Song.create(name: "Distracted", artist: "Annie Dang", genre: "Soul", platform: "Spotify")
song11 = Song.create(name: "Heebiejeebies(Bonus)[feat. Kehlani]", artist: "Amine", genre: "R&B", platform: "Spotify")
song12 = Song.create(name: "2ON", artist: "jetson", genre: "Pop", platform: "SoundCloud")
song13 = Song.create(name: "Holographic", artist: "anbuu", genre: "Funk", platform: "SoundCloud")
song14 = Song.create(name: "Under", artist: "Mac Ayres", genre: "Soul", platform: "Spotify")
song15 = Song.create(name: "would you w/ Bobby Someone", artist: "sem0r", genre: "Soul", platform: "Apple Music")
song16 = Song.create(name: "Where The Flowers Grow (prod. Moo Latte)", artist: "Marie Dahlstrom", genre: "Soul", platform: "Apple Music")
song17 = Song.create(name: "Everything", artist: "Ella Mai", genre: "R&B", platform: "Apple Music")
song18 = Song.create(name: "Breezy feat. MarcLo", artist: "Pastel", genre: "Soul", platform: "Apple Music")
song19 = Song.create(name: "To forget you", artist: "anbuu", genre: "Soul", platform: "SoundCloud")
song20 = Song.create(name: "GOLDA - City Girls (Whereisalex Remix)", artist: "whereisalex", genre: "Soul", platform: "SoundCloud")

song21 = Song.create(name: "Loving", artist: "Surfaces", genre: "Soul", platform: "SoundCloud")
song22 = Song.create(name: "Blue World", artist: "Mac Miller", genre: "Soul", platform: "Apple Music")
song23 = Song.create(name: "Have I Told You", artist: "junior state", genre: "Soul", platform: "SoundCloud")
song24 = Song.create(name: "Gone", artist: "Aruu", genre: "Bounce", platform: "SoundCloud")
song25 = Song.create(name: "Young", artist: "Emeryld", genre: "Soul", platform: "Spotify")
song26 = Song.create(name: "Youngn Lipz - Misunderstood (Cabu 4theclub Edit)", artist: "Cabu", genre: "Rap", platform: "SoundCloud")
song27 = Song.create(name: "Down Time w Malik Elijah", artist: "Alex Martian", genre: "Rap", platform: "SoundCloud")
song28 = Song.create(name: "Buying Time", artist: "Lucky Daye", genre: "Soul", platform: "Apple Music")
song29 = Song.create(name: "jealously", artist: "YAYYOUNG", genre: "Soul", platform: "SoundCloud")
song30 = Song.create(name: "Ame w/ Omar Duro", artist: "singularis", genre: "Bounce", platform: "SoundCloud")
song31 = Song.create(name: "Garden (Prod. by Cuco & Melvv)", artist: "Grady", genre: "Soul", platform: "Spotify")
song32 = Song.create(name: "what", artist: "tenkai", genre: "Bounce", platform: "SoundCloud")
song33 = Song.create(name: "ILL BE YOURS feat. Aaliyah Allah", artist: "HXRY", genre: "R&B", platform: "SoundCloud")
song34 = Song.create(name: "Dive Within", artist: "Dayebeats", genre: "Jazz", platform: "SoundCloud")
song35 = Song.create(name: "Ephemeral~", artist: "Aruu", genre: "Bounce", platform: "SoundCloud")
song36 = Song.create(name: "Sugar (Remix)", artist: "JJ", genre: "R&B", platform: "SoundCloud")
song37 = Song.create(name: "TRUST NOBODY", artist: "Hippie Sabotage", genre: "Electronic", platform: "Spotify")
song38 = Song.create(name: "SHAWTY", artist: "JULIAN AVILA", genre: "Chill Hop", platform: "SoundCloud")
song39 = Song.create(name: "Dive", artist: "Valleyz", genre: "Bounce", platform: "SoundCloud")
song40 = Song.create(name: "Good News", artist: "Mac Miller", genre: "Rap", platform: "Apple Music")

song41 = Song.create(name: "Sidewalk w/ shortfatty & enuar", artist: "anbuu", genre: "Bounce", platform: "SoundCloud")
song42 = Song.create(name: "Boyz Are Dumb", artist: "Tash", genre: "Pop", platform: "Spotify")
song43 = Song.create(name: "Seal Salt (OZNE Edit)", artist: "Bohkeh", genre: "Soul", platform: "SoundCloud")
song44 = Song.create(name: "mi ka", artist: "some people", genre: "Soul", platform: "SoundCloud")
song45 = Song.create(name: "Know Your Worth", artist: "Khalid", genre: "Pop", platform: "Apple Music")
song46 = Song.create(name: "bugaboo (camoufly's take)", artist: "camoufly", genre: "Bounce", platform: "SoundCloud")
song47 = Song.create(name: "Lots of Bands", artist: "Sofasound", genre: "Pop", platform: "SoundCloud")
song48 = Song.create(name: "Owe Me Back", artist: "SUA", genre: "House", platform: "SoundCloud")
song49 = Song.create(name: "Glow Up", artist: "ThatKidMaz Ft. Jordan Dennis (DUAN remix)", genre: "House", platform: "SoundCloud")
song50 = Song.create(name: "Summertime", artist: "public library commute", genre: "Pop", platform: "Spotify")
song51 = Song.create(name: "Down For You", artist: "Cosmo's Midnight X Ruel", genre: "Pop", platform: "Spotify")

songplaylist1 = SongPlaylist.create(song_id: 1, playlist_id: 1)
songplaylist2 = SongPlaylist.create(song_id: 2, playlist_id: 1)
songplaylist3 = SongPlaylist.create(song_id: 3, playlist_id: 1)
songplaylist4 = SongPlaylist.create(song_id: 4, playlist_id: 1)
songplaylist5 = SongPlaylist.create(song_id: 5, playlist_id: 1)
songplaylist6 = SongPlaylist.create(song_id: 6, playlist_id: 1)
songplaylist7 = SongPlaylist.create(song_id: 7, playlist_id: 1)
songplaylist8 = SongPlaylist.create(song_id: 8, playlist_id: 1)
songplaylist9 = SongPlaylist.create(song_id: 9, playlist_id: 1)
songplaylist10 = SongPlaylist.create(song_id: 10, playlist_id: 1)
songplaylist11 = SongPlaylist.create(song_id: 11, playlist_id: 1)
songplaylist12 = SongPlaylist.create(song_id: 12, playlist_id: 1)
songplaylist13 = SongPlaylist.create(song_id: 13, playlist_id: 1)
songplaylist14 = SongPlaylist.create(song_id: 14, playlist_id: 1)
songplaylist15 = SongPlaylist.create(song_id: 15, playlist_id: 1)
songplaylist16 = SongPlaylist.create(song_id: 16, playlist_id: 1)
songplaylist17 = SongPlaylist.create(song_id: 17, playlist_id: 1)
songplaylist18 = SongPlaylist.create(song_id: 18, playlist_id: 1)
songplaylist19 = SongPlaylist.create(song_id: 19, playlist_id: 1)
songplaylist20 = SongPlaylist.create(song_id: 20, playlist_id: 1)

songplaylist21 = SongPlaylist.create(song_id: 21, playlist_id: 2)
songplaylist22 = SongPlaylist.create(song_id: 22, playlist_id: 2)
songplaylist23 = SongPlaylist.create(song_id: 23, playlist_id: 2)
songplaylist24 = SongPlaylist.create(song_id: 24, playlist_id: 2)
songplaylist25 = SongPlaylist.create(song_id: 25, playlist_id: 2)
songplaylist26 = SongPlaylist.create(song_id: 26, playlist_id: 2)
songplaylist27 = SongPlaylist.create(song_id: 27, playlist_id: 2)
songplaylist28 = SongPlaylist.create(song_id: 28, playlist_id: 2)
songplaylist29 = SongPlaylist.create(song_id: 29, playlist_id: 2)
songplaylist30 = SongPlaylist.create(song_id: 30, playlist_id: 2)
songplaylist31 = SongPlaylist.create(song_id: 31, playlist_id: 2)
songplaylist32 = SongPlaylist.create(song_id: 32, playlist_id: 2)
songplaylist33 = SongPlaylist.create(song_id: 33, playlist_id: 2)
songplaylist34 = SongPlaylist.create(song_id: 34, playlist_id: 2)
songplaylist35 = SongPlaylist.create(song_id: 35, playlist_id: 2)
songplaylist36 = SongPlaylist.create(song_id: 36, playlist_id: 2)
songplaylist37 = SongPlaylist.create(song_id: 37, playlist_id: 2)
songplaylist38 = SongPlaylist.create(song_id: 38, playlist_id: 2)
songplaylist39 = SongPlaylist.create(song_id: 39, playlist_id: 2)
songplaylist40 = SongPlaylist.create(song_id: 40, playlist_id: 2)

songplaylist41 = SongPlaylist.create(song_id: 41, playlist_id: 3)
songplaylist42 = SongPlaylist.create(song_id: 42, playlist_id: 3)
songplaylist43 = SongPlaylist.create(song_id: 43, playlist_id: 3)
songplaylist44 = SongPlaylist.create(song_id: 44, playlist_id: 3)
songplaylist45 = SongPlaylist.create(song_id: 45, playlist_id: 3)
songplaylist46 = SongPlaylist.create(song_id: 46, playlist_id: 3)
songplaylist47 = SongPlaylist.create(song_id: 47, playlist_id: 3)
songplaylist48 = SongPlaylist.create(song_id: 48, playlist_id: 3)
songplaylist49 = SongPlaylist.create(song_id: 49, playlist_id: 3)
songplaylist50 = SongPlaylist.create(song_id: 50, playlist_id: 3)
songplaylist51 = SongPlaylist.create(song_id: 51, playlist_id: 3)
